title: NCAA March Madness Game Prediction
description: In this project, I used data from NCAA games from the previous three seasons to create a logistic regression model in Python that would predict the winners of future games.
remote_theme: andrewbanchich/vscode-dark-plus-jekyll
plugins:
  - jekyll-remote-theme
markdown: kramdown
highlighter: rouge
