title: NCAA March Madness Game Prediction
description: In this project, I used data from NCAA games from the previous three seasons to create a logistic regression model in Python that would predict the winners of future games.
remote_theme: pages-themes/cayman@v0.2.0   # or pages-themes/minimal@v0.2.0, pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
markdown: kramdown
highlighter: rouge
