title: NCAA March Madness Game Prediction
description: NCAA game outcome predictions with Python logistic regression by Abdullah Subuh
remote_theme: pages-themes/slate@v0.2.0   # darker than minimal
plugins:
  - jekyll-remote-theme
markdown: kramdown
highlighter: rouge
